FROM nixos/nix

# https://lazamar.co.uk/nix-versions/?channel=nixpkgs-unstable&package=restic
RUN nix-env -i restic-0.9.6 -f https://github.com/NixOS/nixpkgs-channels/archive/1975b8687474764c157e6a220fdcad2c5dc348a1.tar.gz
